// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/echo": {
            "post": {
                "description": "Echo",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Basic"
                ],
                "summary": "Echo",
                "parameters": [
                    {
                        "description": "Echo",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Echo",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/game/ranks": {
            "post": {
                "description": "Get ranks",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Game"
                ],
                "summary": "Get ranks",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/request.GetRanksRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_GetRanksResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_Empty"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/response.BaseResponse-response_Empty"
                        }
                    }
                }
            }
        },
        "/game/signaling": {
            "get": {
                "description": "Websocket Signaling Server for WebRTC Communication\nUse this endpoint as signaling server url",
                "tags": [
                    "Game"
                ],
                "summary": "Signaling Channel",
                "responses": {}
            }
        },
        "/game/ws": {
            "get": {
                "description": "Websocket Endpoint for In-game Communication\nUse this endpoint as signaling server url",
                "tags": [
                    "Game"
                ],
                "summary": "Game Server",
                "responses": {}
            }
        }
    },
    "definitions": {
        "entities.Score": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                },
                "tetrisUsername": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "wordguessUsername": {
                    "type": "string"
                }
            }
        },
        "request.GetRanksRequest": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                }
            }
        },
        "response.BaseResponse-response_Empty": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.Empty"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.BaseResponse-response_GetRanksResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/response.GetRanksResponse"
                },
                "message": {
                    "type": "string"
                },
                "ok": {
                    "type": "boolean"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "response.Empty": {
            "type": "object"
        },
        "response.GetRanksResponse": {
            "type": "object",
            "properties": {
                "scores": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Score"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"https"},
	Title:            "KHUTHON2023 API",
	Description:      "Khuthon 2023 API Server",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
