basePath: /api
definitions:
  entities.Score:
    properties:
      createdAt:
        type: string
      id:
        type: string
      score:
        type: integer
      tetrisUsername:
        type: string
      updatedAt:
        type: string
      wordguessUsername:
        type: string
    type: object
  request.GetRanksRequest:
    properties:
      page:
        type: integer
    type: object
  response.BaseResponse-response_Empty:
    properties:
      data:
        $ref: '#/definitions/response.Empty'
      message:
        type: string
      ok:
        type: boolean
      status:
        type: integer
    type: object
  response.BaseResponse-response_GetRanksResponse:
    properties:
      data:
        $ref: '#/definitions/response.GetRanksResponse'
      message:
        type: string
      ok:
        type: boolean
      status:
        type: integer
    type: object
  response.Empty:
    type: object
  response.GetRanksResponse:
    properties:
      scores:
        items:
          $ref: '#/definitions/entities.Score'
        type: array
    type: object
info:
  contact: {}
  description: Khuthon 2023 API Server
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: KHUTHON2023 API
  version: "1.0"
paths:
  /echo:
    post:
      consumes:
      - application/json
      description: Echo
      parameters:
      - description: Echo
        in: body
        name: body
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: Echo
          schema:
            type: string
      summary: Echo
      tags:
      - Basic
  /game/ranks:
    post:
      consumes:
      - application/json
      description: Get ranks
      parameters:
      - description: body
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/request.GetRanksRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.BaseResponse-response_GetRanksResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.BaseResponse-response_Empty'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.BaseResponse-response_Empty'
      summary: Get ranks
      tags:
      - Game
  /game/signaling:
    get:
      description: |-
        Websocket Signaling Server for WebRTC Communication
        Use this endpoint as signaling server url
      responses: {}
      summary: Signaling Channel
      tags:
      - Game
  /game/ws:
    get:
      description: |-
        Websocket Endpoint for In-game Communication
        Use this endpoint as signaling server url
      responses: {}
      summary: Game Server
      tags:
      - Game
schemes:
- https
swagger: "2.0"
